.TH CCONVERTER 1 "March 05, 2011" cconverter "Linux User's Manual"
.SH NAME
cconverter \- a simple currency converter
.SH SYNOPSIS
.br
.B cconverter
[\fIOPTIONS\fR]

.SH DESCRIPTION
.B Currency Converter
is a simple currency converter written in in pyhton.
It provides both a graphical and a console interface for converting various
currencies. The graphical interface uses Gtk and PyGtk.

.SH OPTIONS
A summary of the options supported by \fBconverter\fR is included below.

.TP
\fB\-\-version\fR
Show the program version number and exit.
.TP
\fB\-h\fR \fB\-\-help\fR
Show a help message and exit
.TP
\fB\-c\fR \fB\-\-currencies\fR
Display a list of supported currencies
.TP
\fB\-r\fR \fB\-\-rate\fR
Apply this to omitt the amount. Returns the current exchange-rate
.TP
\fB\-\-gtk\fR
Run the Gtk interface

.SH BUGS
Issues and bugs can be reported on github:
.IP
https://github.com/ebethron/cconverter/issues

.SH AUTHOR
Einar Uvsløkk \- <einar.uvslokk@linux.com>
