# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/mnt/debris/devel/repo/git/cconverter/data/ui/Ui_MainWindow.ui'
#
# Created: Mon Jul 25 02:14:30 2011
#      by: pyside-uic 0.2.8 running on PySide 1.0.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(390, 380)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.inputLabel = QtGui.QLabel(self.centralwidget)
        self.inputLabel.setObjectName("inputLabel")
        self.verticalLayout.addWidget(self.inputLabel)
        self.inputValue = QtGui.QLineEdit(self.centralwidget)
        self.inputValue.setObjectName("inputValue")
        self.verticalLayout.addWidget(self.inputValue)
        self.calculator = QtGui.QWidget(self.centralwidget)
        self.calculator.setObjectName("calculator")
        self.verticalLayout.addWidget(self.calculator)
        self.sourceLabel = QtGui.QLabel(self.centralwidget)
        self.sourceLabel.setObjectName("sourceLabel")
        self.verticalLayout.addWidget(self.sourceLabel)
        self.sourceCombo = QtGui.QComboBox(self.centralwidget)
        self.sourceCombo.setObjectName("sourceCombo")
        self.verticalLayout.addWidget(self.sourceCombo)
        self.targetLabel = QtGui.QLabel(self.centralwidget)
        self.targetLabel.setObjectName("targetLabel")
        self.verticalLayout.addWidget(self.targetLabel)
        self.targetCombo = QtGui.QComboBox(self.centralwidget)
        self.targetCombo.setObjectName("targetCombo")
        self.verticalLayout.addWidget(self.targetCombo)
        self.responseLabel1 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.responseLabel1.setFont(font)
        self.responseLabel1.setText("")
        self.responseLabel1.setAlignment(QtCore.Qt.AlignCenter)
        self.responseLabel1.setObjectName("responseLabel1")
        self.verticalLayout.addWidget(self.responseLabel1)
        self.responseLabel2 = QtGui.QLabel(self.centralwidget)
        self.responseLabel2.setText("")
        self.responseLabel2.setAlignment(QtCore.Qt.AlignCenter)
        self.responseLabel2.setObjectName("responseLabel2")
        self.verticalLayout.addWidget(self.responseLabel2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.buttonHBox = QtGui.QHBoxLayout()
        self.buttonHBox.setObjectName("buttonHBox")
        self.aboutButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aboutButton.sizePolicy().hasHeightForWidth())
        self.aboutButton.setSizePolicy(sizePolicy)
        self.aboutButton.setObjectName("aboutButton")
        self.buttonHBox.addWidget(self.aboutButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.buttonHBox.addItem(spacerItem1)
        self.convertButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.convertButton.sizePolicy().hasHeightForWidth())
        self.convertButton.setSizePolicy(sizePolicy)
        self.convertButton.setObjectName("convertButton")
        self.buttonHBox.addWidget(self.convertButton)
        self.verticalLayout.addLayout(self.buttonHBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionConvert = QtGui.QAction(MainWindow)
        self.actionConvert.setObjectName("actionConvert")
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionCalc = QtGui.QAction(MainWindow)
        self.actionCalc.setCheckable(True)
        self.actionCalc.setObjectName("actionCalc")
        self.actionClear = QtGui.QAction(MainWindow)
        self.actionClear.setObjectName("actionClear")
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.toolBar.addAction(self.actionConvert)
        self.toolBar.addAction(self.actionQuit)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCalc)
        self.toolBar.addAction(self.actionClear)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionHelp)
        self.toolBar.addAction(self.actionAbout)
        self.inputLabel.setBuddy(self.inputValue)
        self.sourceLabel.setBuddy(self.sourceCombo)
        self.targetLabel.setBuddy(self.targetCombo)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.aboutButton, QtCore.SIGNAL("clicked()"), MainWindow.showAbout)
        QtCore.QObject.connect(self.convertButton, QtCore.SIGNAL("clicked()"), MainWindow.convert)
        QtCore.QObject.connect(self.actionAbout, QtCore.SIGNAL("triggered()"), MainWindow.showAbout)
        QtCore.QObject.connect(self.actionCalc, QtCore.SIGNAL("toggled(bool)"), MainWindow.toggleCalc)
        QtCore.QObject.connect(self.actionClear, QtCore.SIGNAL("triggered()"), MainWindow.clearInput)
        QtCore.QObject.connect(self.actionConvert, QtCore.SIGNAL("triggered()"), MainWindow.convert)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL("triggered()"), MainWindow.close)
        QtCore.QObject.connect(self.actionHelp, QtCore.SIGNAL("triggered()"), MainWindow.showHelpContents)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.inputValue, self.sourceCombo)
        MainWindow.setTabOrder(self.sourceCombo, self.targetCombo)
        MainWindow.setTabOrder(self.targetCombo, self.convertButton)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "CConverter", None, QtGui.QApplication.UnicodeUTF8))
        self.inputLabel.setText(QtGui.QApplication.translate("MainWindow", "<b>Convert this value</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.sourceLabel.setText(QtGui.QApplication.translate("MainWindow", "<b>From this currency</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.targetLabel.setText(QtGui.QApplication.translate("MainWindow", "<b>To this currency</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.aboutButton.setText(QtGui.QApplication.translate("MainWindow", "&About", None, QtGui.QApplication.UnicodeUTF8))
        self.convertButton.setText(QtGui.QApplication.translate("MainWindow", "&Convert", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConvert.setText(QtGui.QApplication.translate("MainWindow", "&Convert", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConvert.setToolTip(QtGui.QApplication.translate("MainWindow", "Convert input value", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConvert.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Return", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setToolTip(QtGui.QApplication.translate("MainWindow", "Quit application", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCalc.setText(QtGui.QApplication.translate("MainWindow", "Calc&ulator", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCalc.setToolTip(QtGui.QApplication.translate("MainWindow", "Toggle calculator", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCalc.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+C", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear.setText(QtGui.QApplication.translate("MainWindow", "C&lear", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear.setToolTip(QtGui.QApplication.translate("MainWindow", "Clear input value", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear.setShortcut(QtGui.QApplication.translate("MainWindow", "Del", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setText(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setToolTip(QtGui.QApplication.translate("MainWindow", "Help contents", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setShortcut(QtGui.QApplication.translate("MainWindow", "F1", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "&About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setToolTip(QtGui.QApplication.translate("MainWindow", "About this application", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setShortcut(QtGui.QApplication.translate("MainWindow", "F12", None, QtGui.QApplication.UnicodeUTF8))

